server:
  port: 80
spring:
  application:
    name: cloud-orderOpenFeign-service
eureka:
  client:
  # 表示将自己注册进Eureka 默认是true
    register-with-eureka: true
    #是否在EurekaServer抓取已有的注册信息，单节点无所谓 集群必须设置true才能配合robbon负载均衡
    fetch-registry: true
    service-url:
      #单机版defaultZone: http://localhost:7001/eureka
          # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 10000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 10000
logging:
  level:
    # feign日志以什么级别监控哪个接口
   com.xwtec.springcloud.service.OrderFeigenService: debug
